# Generated by Django 6.1 on 2026-09-15 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=100, verbose_name='Insumo')),
                ('stock_actual', models.FloatField(verbose_name='Stock actual')),
                ('venta_proyectada', models.FloatField(verbose_name='Venta proyectada (M$)')),
                ('estado', models.CharField(choices=[('Aceptado: Produccion requerida', 'Producción requerida'), ('Rechazado: Stock suficiente', 'Stock suficiente'), ('Rechazado: Alerta de sobrestock', 'Alerta de sobrestock'), ('Error: Valores no validos', 'Valores no válidos')], max_length=40, verbose_name='Estado')),
                ('detalle', models.CharField(max_length=200, verbose_name='Detalle')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de evaluación')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-fecha'],
            },
        ),
    ]
