# Generated by Django 6.1 on 2026-09-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='stock_actual',
            field=models.FloatField(blank=True, null=True, verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='venta_proyectada',
            field=models.FloatField(blank=True, null=True, verbose_name='Venta proyectada (M$)'),
        ),
    ]
